// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqnMhZ3u-z1hqlqGod7qUo7bb6PLIF_dI',
    appId: '1:610391208242:web:31647d9cc6a9ee9b47a72b',
    messagingSenderId: '610391208242',
    projectId: 'dynamic-dam',
    authDomain: 'dynamic-dam.firebaseapp.com',
    databaseURL: 'https://dynamic-dam-default-rtdb.firebaseio.com',
    storageBucket: 'dynamic-dam.firebasestorage.app',
    measurementId: 'G-GJFL7VPG07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqDP759Nnk-1ANecTrRVpkLC_sN7y7le4',
    appId: '1:610391208242:android:467e405ae9a2c50347a72b',
    messagingSenderId: '610391208242',
    projectId: 'dynamic-dam',
    databaseURL: 'https://dynamic-dam-default-rtdb.firebaseio.com',
    storageBucket: 'dynamic-dam.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqnMhZ3u-z1hqlqGod7qUo7bb6PLIF_dI',
    appId: '1:610391208242:web:8717c3201bb82b8247a72b',
    messagingSenderId: '610391208242',
    projectId: 'dynamic-dam',
    authDomain: 'dynamic-dam.firebaseapp.com',
    databaseURL: 'https://dynamic-dam-default-rtdb.firebaseio.com',
    storageBucket: 'dynamic-dam.firebasestorage.app',
    measurementId: 'G-NMSX4577WH',
  );
}
